language: java
jdk:
  - oraclejdk8
sudo: required
services:
  - docker

before_install:
  - sudo apt-get update -qq
  - sudo apt-get -y -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confnew install docker-engine
  - env
# Pre-fetch docker images - seems to need to be done before docker env vars are set
  
  - docker pull rabbitmq:3.5.3
  - docker pull mongo:3.1.5
  
# Update env vars required by testcontainers
  - export DOCKER_HOST=tcp://127.0.0.1:2375
  - export DOCKER_TLS_VERIFY=0
  - env
  
  addons:
  sonarqube:
    organization: "rogerioalves21@gmail.com"
    branches:
      - master
script:
  - sonar-scanner

#after_script:
  #- "[[ $TRAVIS_PULL_REQUEST == false ]] && mvn -Pjacoco package sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONARQUBE_TOKEN}"
